package com.figuritas.panini;

public enum Seleccion {
	//GRUPO A
	QATAR, ECUADOR, SENEGAL, PAISES_BAJOS, 
	// GRUPO B
	INGLATERRA, IRAN, ESTADOS_UNIDOS, GALES,
	//GRUPO C 
	ARGENTINA, ARABIA, MEXICO, POLONIA,
	// GRUPO D
	FRANCIA, AUSTRALIA, DINAMARCA, TUNEZ,
	// GRUPO E
	ESPAÑA, COSTA_RICA, ALEMANIA, JAPON,
	// GRUPO F
	BELGICA, CANADA, MARRUECOS, CROACIA,
	// GRUPO G
	BRASIL, SERBIA, SUIZA, CAMERON,
	// GRUPO H
	PORTUGAL, GHANA, URUGUAY, COREA_DEL_SUR;
}
